ApiScript = {
  SOI ~ (Schema | Api)* ~ EOI
}
Schema    = { "schema" ~ IDENT ~ "=" ~ SchemaDef }
SchemaDef = { TypeDef | "{" ~ Fields ~ "}" }
Fields    = { (Field ~ "?"?)* }
TypeDef   = {
  Primitive ~ ("#" ~ Format)?
| List
| IDENT
}
List      = { "[" ~ TypeDef ~ "]" }

Format    = { "date" | "date-time" | "password" | "byte" | "binary" | IDENT }
Field     = { IDENT ~ ":" ~ TypeDef }
Primitive = { "string" | "number" | "integer" | "boolean" }

Api         =  { "api" ~ IDENT ~ Version ~ "{" ~ PathDef* ~ "}" }
Version     = @{ "\"" ~ (ASCII_DIGIT | ".")+ ~ "\"" }
PathDef     =  { "path" ~ Path ~ "{" ~ Endpoint* ~ "}" }
Path        =  { "\"" ~ PATH ~ "\"" }
Endpoint    =  { Method ~ OperationId ~ "(" ~ Parameters? ~ ")" ~ "{" ~ Responses ~ "}" }
Method      =  { "GET" | "PUT" | "POST" | "DELETE" | "PATCH" }
OperationId =  { IDENT }
Parameters  =  { "foo" }
Responses   = _{ Response* }
Response    =  { HttpCode ~ ":" ~ TypeDef }

HttpCode   = @{ ASCII_DIGIT+ }
PATH       = @{ (ASCII_ALPHANUMERIC | "/")* }
IDENT      = @{ ASCII_ALPHA ~ ASCII_ALPHANUMERIC* }
WHITESPACE = _{ " " | NEWLINE }
