ApiScript = { SOI ~ (Schema | Api | Type)* ~ EOI }

// Types
Schema         = { "schema" ~ Identifier ~ "{" ~ Fields ~ "}" }
Type           = { "type" ~ Identifier ~ ":" ~ TypeDefinition }
TypeDefinition = { Kind | List | Identifier }
Kind           = { Primitive ~ ("#" ~ Format)? }
Fields         = { Field* }
Field          = { Identifier ~ ":" ~ TypeDefinition ~ Optional? }
Optional       = { "?" }
List           = { "[" ~ TypeDefinition ~ "]" }
Format         = { "date" | "date-time" | "password" | "byte" | "binary" | Identifier }
Primitive      = { "string" | "number" | "integer" | "boolean" }

// Annotations
Annotations = { Annotation* }
Annotation  = { "@" ~ Identifier ~ ("(" ~ Value ~ ")")? }

// Values
Value           = _{ String | ArrayValue | Identifier | StructuredValue | NumberValue }
ArrayValue      = @{ "[" ~ ((String | TypeDefinition) ~ ",")* }
NumberValue     = @{ ASCII_DIGIT* }
StructuredValue =  { "{" ~ ValueField* ~ "}" }
ValueField      =  { Identifier ~ ":" ~ (String | ArrayValue | Identifier | NumberValue) }

// Api
Api         =  { Annotations ~ "api" ~ String ~ Version ~ "{" ~ ApiBody ~ "}" }
ApiBody     =  { (ApiPath | Server)* }
Server      =  { "server" ~ String ~ ("{" ~ "}")? }
Version     = _{ String }
ApiPath     =  { "path" ~ "\"" ~ UrlPath ~ "\"" ~ "{" ~ Endpoints ~ "}" }
Endpoints   =  { Endpoint* }
UrlPath     =  { Path }
Endpoint    =  { Annotations ~ Method ~ OperationId ~ "(" ~ Parameters? ~ ")" ~ "{" ~ Responses ~ "}" }
Method      =  { "GET" | "PUT" | "POST" | "DELETE" | "PATCH" }
OperationId = _{ Identifier }
Parameters  =  { Parameter ~ ("," ~ Parameter)* }
Parameter   =  { Annotations ~ Identifier ~ ":" ~ TypeDefinition ~ Optional? }
Responses   =  { Response* }
Response    =  { Annotations ~ (HttpCode | "default") ~ ":" ~ TypeDefinition }

// General Patterns
HttpCode   = @{ ASCII_DIGIT{3} }
Path       = @{ (ASCII_ALPHANUMERIC | "/" | "{" | "}")* }
Identifier = @{ ASCII_ALPHA ~ ASCII_ALPHANUMERIC* }
String     = @{ "\"" ~ (!("\"") ~ ANY)* ~ "\"" }

// VERSION    = _{ ASCII_ALPHANUMERIC | "." }
WHITESPACE = _{ " " | NEWLINE }
COMMENT    = _{ "//" ~ (!NEWLINE ~ ANY)* }
